
-----------------------------------------------------------------------
---- Automatically generated by generate_premake.py. Do not edit ! ----
-----------------------------------------------------------------------

project("libavcodec")
  uuid("9DB2830C-D326-48ED-B4CC-08EA6A1B7272")
  kind("StaticLib")
  language("C")
  ffmpeg_common()

  links({
    "libavutil",
  })
  -- libavcodec/Makefile:
  --   HEADERS:
  files({
    "ac3_parser.h",
    "adts_parser.h",
    "avcodec.h",
    "avdct.h",
    "avfft.h",
    "bsf.h",
    "codec.h",
    "codec_desc.h",
    "codec_id.h",
    "codec_par.h",
    "d3d11va.h",
    "dirac.h",
    "dv_profile.h",
    "dxva2.h",
    "jni.h",
    "mediacodec.h",
    "packet.h",
    "qsv.h",
    "vaapi.h",
    "vdpau.h",
    "version.h",
    "videotoolbox.h",
    "vorbis_parser.h",
    "xvmc.h",
  })
  -- libavcodec/Makefile:
  --   OBJS:
  files({
    "ac3_parser.c",
    "adts_parser.c",
    "allcodecs.c",
    "avcodec.c",
    "avdct.c",
    "avpacket.c",
    "avpicture.c",
    "bitstream.c",
    "bitstream_filter.c",
    "bitstream_filters.c",
    "bsf.c",
    "codec_desc.c",
    "codec_par.c",
    "d3d11va.c",
    "decode.c",
    "dirac.c",
    "dv_profile.c",
    "encode.c",
    "imgconvert.c",
    "jni.c",
    "mathtables.c",
    "mediacodec.c",
    "mpeg12framerate.c",
    "options.c",
    "parser.c",
    "parsers.c",
    "profiles.c",
    "qsv_api.c",
    "raw.c",
    "utils.c",
    "vorbis_parser.c",
    "xiph.c",
  })
  -- libavcodec/Makefile:
  --   OBJS-yes:
  files({
    "faandct.c",
    "faanidct.c",
    "fdctdsp.c",
    "jfdctfst.c",
    "jfdctint.c",
    "idctdsp.c",
    "simple_idct.c",
    "jrevdct.c",
    "mdct_float.c",
    "mdct_fixed_32.c",
    "sinewin.c",
    "wma_freqs.c",
    "wmaprodec.c",
    "wma.c",
    "wma_common.c",
    "wmaprodec.c",
    "wma.c",
    "wma_common.c",
    "null_bsf.c",
    "file_open.c",
    "pthread.c",
    "pthread_slice.c",
    "pthread_frame.c",
    "avfft.c",
    "fft_float.c",
    "fft_fixed_32.c",
    "fft_init_table.c",
  })
  -- libavcodec/aarch64/Makefile:
  --   OBJS-yes:
  files({
    "aarch64/fft_init_aarch64.c",
    "aarch64/idctdsp_init_aarch64.c",
  })
  -- libavcodec/x86/Makefile:
  --   OBJS:
  files({
    "x86/constants.c",
  })
  -- libavcodec/x86/Makefile:
  --   OBJS-yes:
  files({
    "x86/fdctdsp_init.c",
    "x86/fft_init.c",
    "x86/idctdsp_init.c",
  })
  -- libavcodec/x86/Makefile:
  --   MMX-OBJS-yes:
  files({
    "x86/fdct.c",
  })
